//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sousFamille
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_sousFamille()
        {
            this.tbl_rub1 = new HashSet<tbl_rub1>();
        }
    
        public int idSousFamille { get; set; }
        public string nomSousFamille { get; set; }
        public double valeur { get; set; }
        public string unité { get; set; }
        public Nullable<double> max { get; set; }
        public string unitéMax { get; set; }
        public string obsSousFamille { get; set; }
        public int idFamille { get; set; }
        public bool isDeleted { get; set; }
        public string codeNom { get; set; }
    
        public virtual tbl_famille tbl_famille { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rub1> tbl_rub1 { get; set; }
    }
}
