//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rub1
    {
        public int idRub1 { get; set; }
        public Nullable<System.DateTime> dateRub1 { get; set; }
        public Nullable<int> designationId { get; set; }
        public Nullable<decimal> honorairesRub1 { get; set; }
        public string deviseRub1 { get; set; }
        public string matriculeFisacalRub1 { get; set; }
        public int idBs { get; set; }
        public string devise_souhaite { get; set; }
        public Nullable<double> montant_change { get; set; }
        public Nullable<int> idSousFamille { get; set; }
        public Nullable<double> montant_estimé { get; set; }
    
        public virtual tbl_bulletinSoin tbl_bulletinSoin { get; set; }
        public virtual tbl_designation tbl_designation { get; set; }
        public virtual tbl_sousFamille tbl_sousFamille { get; set; }
    }
}
