//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rub3
    {
        public int idRub3 { get; set; }
        public Nullable<System.DateTime> dateRub3 { get; set; }
        public string dents { get; set; }
        public string actMedical { get; set; }
        public Nullable<decimal> honorairesRub3 { get; set; }
        public string deviseRub3 { get; set; }
        public string matriculeFiscalRub3 { get; set; }
        public string type { get; set; }
        public int idBs { get; set; }
        public Nullable<double> montant_change3 { get; set; }
        public Nullable<double> montant_estimé3 { get; set; }
    
        public virtual tbl_bulletinSoin tbl_bulletinSoin { get; set; }
    }
}
