//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_adherent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_adherent()
        {
            this.tbl_bulletinSoin = new HashSet<tbl_bulletinSoin>();
            this.tbl_prestataire = new HashSet<tbl_prestataire>();
        }
    
        public int idAdherent { get; set; }
        public string nomAdh { get; set; }
        public string prenomAdh { get; set; }
        public Nullable<long> CIN_PASS { get; set; }
        public string adressAdh { get; set; }
        public string emailAdh { get; set; }
        public Nullable<long> matriculeCnam { get; set; }
        public string status { get; set; }
        public Nullable<long> numTelephone { get; set; }
        public bool isDeleted { get; set; }
        public int police { get; set; }
        public System.DateTime dateAdhesion { get; set; }
        public Nullable<System.DateTime> dateNais { get; set; }
        public string lieuNais { get; set; }
        public string sexeAdherent { get; set; }
        public string situationFamiliale { get; set; }
        public string gouvernorat { get; set; }
        public Nullable<int> codePostal { get; set; }
        public string profession { get; set; }
        public string lieu { get; set; }
        public Nullable<double> salaireBrut { get; set; }
        public Nullable<long> RIB { get; set; }
        public string benefEnCasDeces { get; set; }
        public List<Prestataire> Prestataires { get; set; }
        public List<Prestataire> PrestatairesConjoint { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_bulletinSoin> tbl_bulletinSoin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_prestataire> tbl_prestataire { get; set; }
    }
}
