//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rub2
    {
        public int idRub2 { get; set; }
        public Nullable<System.DateTime> DE { get; set; }
        public Nullable<System.DateTime> DS { get; set; }
        public Nullable<decimal> montantFrais { get; set; }
        public string deviseRub2 { get; set; }
        public string matriculeFiscalRub2 { get; set; }
        public int idBs { get; set; }
        public Nullable<double> montant_change2 { get; set; }
        public Nullable<double> montant_estimé2 { get; set; }
    
        public virtual tbl_bulletinSoin tbl_bulletinSoin { get; set; }
    }
}
