//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bulletinSoin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_bulletinSoin()
        {
            this.tbl_rub1 = new HashSet<tbl_rub1>();
            this.tbl_rub2 = new HashSet<tbl_rub2>();
            this.tbl_rub3 = new HashSet<tbl_rub3>();
        }
    
        public int idBs { get; set; }
        public bool isDeleted { get; set; }
        public int idAdherent { get; set; }
        public int idPrestataire { get; set; }
        public string status { get; set; }
        public long numBs { get; set; }
        public string path { get; set; }
    
        public virtual tbl_adherent tbl_adherent { get; set; }
        public virtual tbl_prestataire tbl_prestataire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rub1> tbl_rub1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rub2> tbl_rub2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rub3> tbl_rub3 { get; set; }
    }
}
