//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_designation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_designation()
        {
            this.tbl_rub1 = new HashSet<tbl_rub1>();
        }
    
        public int designationId { get; set; }
        public string designationNo { get; set; }
        public string designationNom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rub1> tbl_rub1 { get; set; }
    }
}
