//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_prestataire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_prestataire()
        {
            this.tbl_bulletinSoin = new HashSet<tbl_bulletinSoin>();
        }
    
        public int idPrestataire { get; set; }
        public string codePrestataire { get; set; }
        public string nomPres { get; set; }
        public string prenomPres { get; set; }
        public Nullable<System.DateTime> dateNais { get; set; }
        public string adressPres { get; set; }
        public int idAdherent { get; set; }
        public string sexe { get; set; }
        public string profession { get; set; }
        public string employeur { get; set; }
    
        public virtual tbl_adherent tbl_adherent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_bulletinSoin> tbl_bulletinSoin { get; set; }
    }
}
